apiVersion: apps/v1
kind: Deployment
metadata:
  name: tunesnatch-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: tunesnatch
  template:
    metadata:
      labels:
        app: tunesnatch
    spec:
      containers:
        - name: tunesnatch
          image: dilipdare/tunesnatch-app:v1
          ports:
            - containerPort: 8080
          env:
            - name: YOUTUBE_API_KEY
              valueFrom:
                secretKeyRef:
                  name: youtube-api-key
                  key: api-key
          volumeMounts:
            - name: downloads
              mountPath: /root/Downloads
      volumes:
        - name: downloads
          emptyDir: {}